namespace InvoiceApp.Api.Diagnostics;

/// <summary>
/// Per docs/SAD.md section 78: each request gets a correlation identifier that propagates through
/// the request, application operation and logging. Uses HttpContext.TraceIdentifier (already
/// unique per request, generated by the framework) rather than inventing a second ID - every log
/// statement made while handling the request is wrapped in a logging scope carrying it, and it is
/// echoed back in the X-Correlation-Id response header so a caller can reference it when reporting
/// an issue.
/// </summary>
public sealed class CorrelationIdMiddleware(RequestDelegate next)
{
    private const string HeaderName = "X-Correlation-Id";

    public async Task InvokeAsync(HttpContext context, ILogger<CorrelationIdMiddleware> logger)
    {
        var correlationId = context.TraceIdentifier;

        context.Response.OnStarting(() =>
        {
            context.Response.Headers[HeaderName] = correlationId;
            return Task.CompletedTask;
        });

        // The message-template overload (not a raw Dictionary) so the scope both renders readably
        // in plain-text console output and exposes CorrelationId as a structured property to
        // providers that support it (Seq, Application Insights, etc. - docs/SAD.md section 76).
        using (logger.BeginScope("CorrelationId:{CorrelationId}", correlationId))
        {
            await next(context);
        }
    }
}
